In [1]:
import pandas as pd

### 데이터 읽어오기
- 웹 문서에서 데이터를 가져오고자 한다.
- 원하는 데이터가 있는 곳의 html tag가 table 이라면 데이터 프레임으로 바로 생성이 가능하다.

In [2]:
# 읽어올 페이지의 주소
site = [
    'https://www.basketball-reference.com/leagues/NBA_2018_games-october.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-november.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-december.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-january.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-february.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-march.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-april.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-may.html',
    'https://www.basketball-reference.com/leagues/NBA_2018_games-june.html',
]

In [21]:
# 지정된 웹 문서를 통해 데이터 프레임을 생성한다.
# read_html : 지정된 웹페이지에서 table 태그를 이용해 데이터프레임을 생성한다.
# 하나의 html 문서안에는 table 태그가 다수가 있을 수 있으므로
# table 태그 하나당 하나의 데이터 프레임이 생성되고
# 데이터 프레임들이 리스트에 담겨져서 반환된다. 
tables = pd.read_html(site[0])
tables[0]

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,"Tue, Oct 17, 2017",8:01p,Boston Celtics,99,Cleveland Cavaliers,102,Box Score,NaN,20562,Quicken Loans Arena,NaN
1,"Tue, Oct 17, 2017",10:30p,Houston Rockets,122,Golden State Warriors,121,Box Score,NaN,19596,Oracle Arena,NaN
2,"Wed, Oct 18, 2017",7:00p,Charlotte Hornets,90,Detroit Pistons,102,Box Score,NaN,20491,Little Caesars Arena,NaN
3,"Wed, Oct 18, 2017",7:00p,Brooklyn Nets,131,Indiana Pacers,140,Box Score,NaN,15008,Bankers Life Fieldhouse,NaN
4,"Wed, Oct 18, 2017",7:00p,Miami Heat,109,Orlando Magic,116,Box Score,NaN,18846,Amway Center,NaN
...,...,...,...,...,...,...,...,...,...,...,...
99,"Mon, Oct 30, 2017",10:30p,Golden State Warriors,141,Los Angeles Clippers,113,Box Score,NaN,19068,STAPLES Center,NaN
100,"Tue, Oct 31, 2017",7:00p,Sacramento Kings,83,Indiana Pacers,101,Box Score,NaN,12245,Bankers Life Fieldhouse,NaN
101,"Tue, Oct 31, 2017",7:30p,Phoenix Suns,122,Brooklyn Nets,114,Box Score,NaN,12936,Barclays Center,NaN
102,"Tue, Oct 31, 2017",8:00p,Oklahoma City Thunder,110,Milwaukee Bucks,91,Box Score,NaN,16713,BMO Harris Bradley Center,NaN
103,"Tue, Oct 31, 2017",10:30p,Detroit Pistons,93,Los Angeles Lakers,113,Box Score,NaN,17569,STAPLES Center,NaN

In [6]:
# 데이터 프레임을 담을 리스트
df_list = []
# 사이트의 주소 만큼 반복한다.
for s1 in site :
    # 해당 페이지에서 데이터 프레임들을 가져온다.
    df_list2 = pd.read_html(s1)
    # 첫 번째 데이터프레임을 추출하여 리스트에 담는다.
    df_list.append(df_list2[0])

In [16]:
# 모은 데이터 프레임들을 하나의 데이터프레임으로 합쳐준다.
df1 = pd.concat(df_list)
# 인덱스를 리셋한다.
df1.reset_index(drop=True, inplace=True)
df1

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,"Tue, Oct 17, 2017",8:01p,Boston Celtics,99,Cleveland Cavaliers,102,Box Score,NaN,20562,Quicken Loans Arena,NaN
1,"Tue, Oct 17, 2017",10:30p,Houston Rockets,122,Golden State Warriors,121,Box Score,NaN,19596,Oracle Arena,NaN
2,"Wed, Oct 18, 2017",7:00p,Charlotte Hornets,90,Detroit Pistons,102,Box Score,NaN,20491,Little Caesars Arena,NaN
3,"Wed, Oct 18, 2017",7:00p,Brooklyn Nets,131,Indiana Pacers,140,Box Score,NaN,15008,Bankers Life Fieldhouse,NaN
4,"Wed, Oct 18, 2017",7:00p,Miami Heat,109,Orlando Magic,116,Box Score,NaN,18846,Amway Center,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1308,"Mon, May 28, 2018",9:00p,Golden State Warriors,101,Houston Rockets,92,Box Score,NaN,18055,Toyota Center,NaN
1309,"Thu, May 31, 2018",9:00p,Cleveland Cavaliers,114,Golden State Warriors,124,Box Score,OT,19596,Oracle Arena,NaN
1310,"Sun, Jun 3, 2018",8:00p,Cleveland Cavaliers,103,Golden State Warriors,122,Box Score,NaN,19596,Oracle Arena,NaN
1311,"Wed, Jun 6, 2018",9:00p,Golden State Warriors,110,Cleveland Cavaliers,102,Box Score,NaN,20562,Quicken Loans Arena,NaN
1312,"Fri, Jun 8, 2018",9:00p,Golden State Warriors,108,Cleveland Cavaliers,85,Box Score,NaN,20562,Quicken Loans Arena,NaN

In [22]:
# 읽어온 데이터 프레임을 저장한다.
df1.to_csv('./data/NBA2028.csv', index=False)