In [1]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

# 0) 관련 모듈 임포트 
import json 
import pandas as pd
import requests
import urllib.request

# key = 5464311301
# 9408629118

C:\Users\pusan\AppData\Local\Temp\ipykernel_17748\906249423.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [85]:
# 1) 고속도로 휴게소별 날씨 정보 Api 서비스를 신청하여라 
url = 'http://data.ex.co.kr/openapi/restinfo/restWeatherList?key=9408629118&type=json&sdate=20220602&stdHour=10'
response = requests.get(url)
print(response)
# print(response.text)

<Response [200]>

In [86]:
# 2) 신청한 api 서비스를 이용하여 특정 날짜(예시-2022년6월2일)의 날씨 데이타를 
# 리스트 딕셔너리 형태로 저장하여라. 
# 아래 예시는 첫번째 고속도로 휴게소의 데이타이다. 
weather = json.loads(response.content)
# weather
weather_list = weather['list']
print(type(weather_list))
weather_list[0]

<class 'list'>

{'unitName': '죽전휴게소',
 'unitCode': '002 ',
 'routeName': '경부선',
 'routeNo': '0010',
 'stdHour': '10',
 'updownTypeCode': 'E',
 'xValue': '127.104165',
 'yValue': '37.332651',
 'sdate': '20220602',
 'snowValue': '-99.000000',
 'addr': '경기도 용인시 수지구 풍덕천동 42-1',
 'tmxValue': '209231.370200',
 'tmyValue': '525935.874890',
 'measurement': '연천',
 'addrCode': '119',
 'addrName': '수원',
 'weatherContents': '구름많음',
 'statusNo': '-99.000000',
 'correctNo': '18.370000',
 'cloudValue': '6.000000',
 'addcloudValue': '2.000000',
 'cloudformValue': '-99.000000',
 'tempValue': '21.100000',
 'dewValue': '13.200000',
 'discomforeValue': '-99.00',
 'sensoryTemp': '-99.000000',
 'highestTemp': '-99.00',
 'highestyearTemp': '-99.00',
 'highestcompTemp': '-99.000000',
 'lowestTemp': '-99.000000',
 'lowestyearTemp': '-99.000000',
 'lowestcompTemp': '-99.000000',
 'rainfallValue': '-99.000000',
 'rainfallstrengthValue': '-99.000000',
 'newsnowValue': '-99.000000',
 'humidityValue': '61.000000',
 'windContents': '27',
 'windValue': '2.100000'}

In [87]:
# 4) 경부선에 위치한 휴게소의 날씨 데이터만 아래와 같이 출력하여라 
for i in weather_list:
    if i['routeName'] == '경부선':
        print(i['routeName'], '-', i['unitName'], i['weatherContents'], i['tempValue'][:4],"도" )

경부선 - 죽전휴게소 구름많음 21.1 도
경부선 - 안성휴게소(서울) 구름많음 21.1 도
경부선 - 옥산휴게소(서울) 구름조금 22.7 도
경부선 - 천안(삼)휴게소(서울) 맑음 21.0 도
경부선 - 죽암휴게소(서울) 맑음 23.4 도
경부선 - 옥천휴게소(서울) 맑음 23.4 도
경부선 - 황간휴게소(서울) 맑음 23.0 도
경부선 - 입장휴게소(서울) 맑음 21.0 도
경부선 - 추풍령휴게소(서울) 맑음 23.0 도
경부선 - 칠곡휴게소(서울) 맑음 25.3 도
경부선 - 경산휴게소(서울) 맑음 24.7 도
경부선 - 건천휴게소(서울) 맑음 26.9 도
경부선 - 언양휴게소(서울) 맑음 28.1 도
경부선 - 신탄진휴게소(서울) 맑음 23.4 도
경부선 - 청원휴게소(서울) 구름조금 22.7 도
경부선 - 금강휴게소(서울) 맑음 21.8 도
경부선 - 만남의광장 구름많음 22.5 도
경부선 - 기흥휴게소 구름많음 21.1 도
경부선 - 안성휴게소(부산) 맑음 21.0 도
경부선 - 망향휴게소 맑음 21.0 도
경부선 - 옥산휴게소(부산) 구름조금 22.7 도
경부선 - 천안휴게소(부산) 맑음 21.0 도
경부선 - 죽암휴게소(부산) 맑음 23.4 도
경부선 - 금강휴게소(부산) 맑음 21.8 도
경부선 - 황간휴게소(부산) 맑음 23.0 도
경부선 - 추풍령휴게소(부산) 맑음 23.0 도
경부선 - 평사휴게소(부산) 맑음 24.7 도
경부선 - 칠곡휴게소(부산) 맑음 25.3 도
경부선 - 건천휴게소(부산) 맑음 26.9 도
경부선 - 언양휴게소(부산) 맑음 28.1 도
경부선 - 옥천휴게소(부산) 맑음 23.4 도
경부선 - 경주휴게소(부산) 맑음 26.9 도

In [33]:
# 5) 데이프레임으로 저장하고 아래와 같이 출력하여라 
df = pd.DataFrame(weather_list)
df

,unitName,unitCode,sdate,stdHour,routeNo,routeName,updownTypeCode,xValue,yValue,tmxValue,...,lowestTemp,lowestyearTemp,lowestcompTemp,rainfallValue,rainfallstrengthValue,newsnowValue,snowValue,humidityValue,windContents,windValue
0,죽전휴게소,002,20220529,10,0010,경부선,E,127.104165,37.332651,209231.370200,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,67.000000,23,1.400000
1,안성휴게소(서울),004,20220529,10,0010,경부선,E,127.132081,37.076107,211745.041377,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,67.000000,23,1.400000
2,옥산휴게소(서울),031,20220529,10,0010,경부선,E,127.371859,36.657168,233247.827579,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,53.000000,36,1.200000
3,천안(삼)휴게소(서울),033,20220529,10,0010,경부선,E,127.173092,36.787388,215450.014074,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,56.000000,29,1.500000
4,죽암휴게소(서울),035,20220529,10,0010,경부선,E,127.430474,36.496560,238568.482957,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,40.000000,7,1.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,서하남휴게소(판교),186,20220529,10,1000,수도권제1순환선,S,127.193039,37.525940,217063.655900,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,68.000000,7,1.100000
183,부여휴게소(서공주),204,20220529,10,1510,서천공주선,S,126.796944,36.258056,181751.583397,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,58.000000,23,1.000000
184,청양휴게소(동서천),209,20220529,10,1510,서천공주선,S,126.989722,36.398611,199078.003547,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,58.000000,23,1.000000
185,벌곡휴게소(논산),043,20220529,10,2510,호남지선,S,127.273793,36.217488,224618.246584,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,40.000000,7,1.700000
186,현풍휴게소(현풍),090,20220529,10,4510,중부내륙지선,S,128.436431,35.701990,330003.845651,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,33.000000,7,1.300000

In [83]:
# 6) 2022년 5월 29~31일 3일간의 데이타를 API 서비스를 이용하여 추출하고 
# 데이타프레임으로 저장하여라
result_list = []
for number in range(29, 32):
    url = f'http://data.ex.co.kr/openapi/restinfo/restWeatherList?key=5464311301&type=json&sdate=202205{number}&stdHour=10'
    print(url)
    response = requests.get(url)
    print(response)
#     print(response.text)
    weather = json.loads(response.content)
    weather_list = weather['list']
    for item in weather_list:
        result_list.append(item)
df = pd.DataFrame(result_list)
df

http://data.ex.co.kr/openapi/restinfo/restWeatherList?key=5464311301&type=json&sdate=20220529&stdHour=10
<Response [200]>
http://data.ex.co.kr/openapi/restinfo/restWeatherList?key=5464311301&type=json&sdate=20220530&stdHour=10
<Response [200]>
http://data.ex.co.kr/openapi/restinfo/restWeatherList?key=5464311301&type=json&sdate=20220531&stdHour=10
<Response [200]>

,unitName,unitCode,routeName,routeNo,stdHour,updownTypeCode,xValue,yValue,sdate,snowValue,...,highestcompTemp,lowestTemp,lowestyearTemp,lowestcompTemp,rainfallValue,rainfallstrengthValue,newsnowValue,humidityValue,windContents,windValue
0,죽전휴게소,002,경부선,0010,10,E,127.104165,37.332651,20220529,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,67.000000,23,1.400000
1,안성휴게소(서울),004,경부선,0010,10,E,127.132081,37.076107,20220529,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,67.000000,23,1.400000
2,옥산휴게소(서울),031,경부선,0010,10,E,127.371859,36.657168,20220529,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,53.000000,36,1.200000
3,천안(삼)휴게소(서울),033,경부선,0010,10,E,127.173092,36.787388,20220529,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,56.000000,29,1.500000
4,죽암휴게소(서울),035,경부선,0010,10,E,127.430474,36.496560,20220529,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,40.000000,7,1.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556,서하남휴게소(판교),186,수도권제1순환선,1000,10,S,127.193039,37.525940,20220531,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,57.000000,23,2.800000
557,부여휴게소(서공주),204,서천공주선,1510,10,S,126.796944,36.258056,20220531,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,50.000000,14,1.200000
558,청양휴게소(동서천),209,서천공주선,1510,10,S,126.989722,36.398611,20220531,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,50.000000,14,1.200000
559,벌곡휴게소(논산),043,호남지선,2510,10,S,127.273793,36.217488,20220531,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,36.000000,20,2.500000
560,현풍휴게소(현풍),090,중부내륙지선,4510,10,S,128.436431,35.701990,20220531,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,27.000000,34,3.400000